<a href="https://colab.research.google.com/github/mounishvatti/machine-learning/blob/main/TensorFlow_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing TensorFlow

In [4]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# Creating Tensors

Each tensor has a datatype and shape.

**Data Types**: float32, int32, string and others.

**Shape:** Represents the dimension of data.

In [5]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

# Rank/Degree of Tensors

Number of dimensions involved in the tensor

In [6]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

**To determine the rank** of the tensor we can call the following method

In [7]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shape of Tensors

In [9]:
rank2_tensor.shape

TensorShape([2, 2])

In [10]:
t = tf.ones([1,2,3])
print(t)
t_new = tf.reshape(t, [2,3,1])
print(t_new)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [11]:
t_flat = tf.reshape(t_new, [-1])
print(t_flat)

tf.Tensor([1. 1. 1. 1. 1. 1.], shape=(6,), dtype=float32)
